name: allenrealestateflutter
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Assets
  font_awesome_flutter: ^8.8.1
  cupertino_icons: ^0.1.3
  google_fonts: ^1.1.0
  # Navigation
  auto_route: ^0.6.7
  # IoC
  get_it: ^4.0.2
  injectable: ^1.0.2
  provider: ^4.3.1
  # Networking
  dio: ^3.0.9
  # Storage
  flutter_secure_storage: ^3.3.3
  # Widgets
  mapbox_search: ^2.0.0
  map_launcher: ^0.12.0
  cached_network_image: ^2.2.0+1
  flutter_svg: ^0.18.0
  # Misc
  path: ^1.7.0
  path_provider: ^1.6.11
  flutter_cache_manager: ^1.4.1
  esys_flutter_share: ^1.0.2
  adobe_xd: ^1.0.0+1
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # App wrappers
  device_preview: ^0.4.5
  # Code generators
  build_runner: ^1.10.0
  auto_route_generator: ^0.6.7
  injectable_generator: ^1.0.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - lib/ui/assets/img/house.png
    - lib/ui/assets/img/farm.png
    - lib/ui/assets/img/building.png
    - lib/ui/assets/icons/ic_filter.svg
